
name: Update Changelog

on:
  pull_request:
    types:
      - closed  # Runs when a PR is merged

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true  # Ensures it only runs on merge
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write access to push changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "@github-ci"
          git config --global user.email "aman043358sagar@gmail.com"

      - name: Update Changelog
        run: |
          #!/bin/bash
          
          FILE="changelog.md"
          
          # Function to check and create the changelog file if it doesn't exist
          function checkOrCreateChangeLog() {
              if [ ! -f "$FILE" ]; then
                  echo "$FILE does not exist. Creating it now..."
                  echo "# Changelog" > "$FILE"
                  echo "" >> "$FILE"
                  echo "Initialized $FILE with a heading."
              fi
          }
          
          # Function to update the changelog with a new entry
          function updateChangeLog() {
              checkOrCreateChangeLog  # Ensure the file exists
              TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
              echo "- $TIMESTAMP: $1" >> "$FILE"
              echo "Changelog updated with: $1"
          }
          
          # Update changelog with PR title
          updateChangeLog "${{ github.event.pull_request.title }}"

      - name: Commit
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}  # Ensure you're on the correct branch
          git add changelog.md
          git commit -m "Update changelog: ${{ github.event.pull_request.title }}"

      - name: Push changes
        run: |
          git push origin ${{ github.event.pull_request.base.ref }}
